name = "elizabethwebinar"
main = "./worker.js"
compatibility_date = "2026-08-08"

[assets]
directory = "."
binding = "ASSETS"

[[kv_namespaces]]
binding = "FAILED_SUBSCRIBERS"
id = "4d299c70fbc5415abba3cfd8b0eb2fee"

[[kv_namespaces]]
binding = "CHECKOUT_LEADS"
id = "257ae505c96c4d47bc74c3ffdc3122e7"

[vars]
BREVO_LIST_ID = "10"
BREVO_FIRSTNAME_KEY = "FIRSTNAME"
KIT_FORM_ID = "9866997"
PHONE_FIELD_KEY = "phone_number"
